version: '3'

services:
    nearby:
      build: .
      restart: always
      links:
        - redis
      depends_on:
        - redis
      ports:
        - '3004:3004'
      environment:
        - REDIS_PORT_6379_TCP_ADDR:"redis:6379"

    redis:
      image: redis:3.2.10
      restart: always
      ports:
        - 6379:6379
