version: '3'

services:
    mongodb:
      image: mongo:latest
      environment:
      - MONGO_INITDB_ROOT_USERNAME=devadmin
      - MONGO_INITDB_ROOT_PASSWORD=devadmin
      - MONGO_INITDB_DATABASE=apateez-nearby
      ports:
        - 27017:27017
      command: mongod --auth
